### ISSUE TITLE
Reddit not present

### ISSUE THREAD

**Issue by rahulunair** [pirate/sites-using-cloudflare#103]
Doesn't reddit use cloud flare?, or have they confirmed that they are not affected, as I do not see reddit here, if not added, kindly add : https://reddit.com to the list as well.

**Comment by Xaekai** [comment]
Reddits leads ops engineer has already clarified the issue via https://github.com/pirate/sites-using-cloudflare/pull/48

**Comment by rahulunair** [comment]
Thanks for the confirmation Xaekai, closing the issue.
