### ISSUE TITLE
Facebook App possible attack vector.

### ISSUE THREAD

**Issue by nuvious** [pirate/sites-using-cloudflare#119]
So not sure if this were a coincidence or otherwise, but the forbes app added itself to my facebook and tried posting things to my page, which resulted in Facebook locking my account down. My actual login for Facebook was not compromised though and Facebook just flagged the Forbes app as a malicious app, so I removed it. Forbes itself isn't on the list but Forbes.ru is. Thought I'd mention that in case you guys, who probably know more about this than I do, know of any way app permission for Facebook or Twitter could be compromised in a similar fashion. Thanks regardless for generating this list!

**Please, do not create duplicate issues**

### DISCLAIMER:
This list contains *all* domains that use cloudflare DNS, not just the cloudflare SSL proxy (the affected service that leaked data).
It's a broad sweeping list that includes everything.  Just because a domain is on the list does not mean the site is compromised.
This list will be narrowed down to the affected domains as I get more information.

### HOW TO REMOVE YOUR SITE
1. verify the site is static and contains no user data (I will remove it immediately once I confirm)  
OR  
1. Verify ownership, send me an email from @yourdomain.com, post a random nonce on the domain, or provide keybase proof
2. Verify you are not using the Cloudflare proxy service

I will not remove sites that contain user data and are returning `server:cloudflare-nginx` in response headers, since they may have been affected.

**Comment by coderobe** [comment]
Facebook uses akamai (afaik), not cloudflare, so this issue can't possibly affect facebook directly.

**Comment by pirate** [comment]
Apps that had facebook auth tokens and are compromised may have leaked facebook auth tokens.
