### ISSUE TITLE
Add: www.gommehd.net

### ISSUE THREAD

**Issue by NexusByte** [pirate/sites-using-cloudflare#123]
www.gommehd.net also uses cloudflare

**Comment by coderobe** [comment]
I just checked and they don't seem to be using the affected services.

**Comment by NexusByte** [comment]
Ping says that they are using cloudflare: http://i.imgur.com/UBJ8d1w.png

**Comment by coderobe** [comment]
Huh, that's weird. Only the www. prefix is routed through CF, the @ record is not routing through them, although it redirects you to the www prefix occasionally.

**Comment by NexusByte** [comment]
I'll edit it to www.gommehd.net

**Comment by pirate** [comment]
done
