### ISSUE TITLE
What specific features were affected?

### ISSUE THREAD

**Issue by turtledude01** [pirate/sites-using-cloudflare#127]
If I use FULL ssl encryption from end to end is it possible that my websites 'were' affected? I have read in many places that it is only the Flexible SSL that was affected, is this true?

**Comment by coderobe** [comment]
Anything that routes through Cloudflare could have possibly leaked data via third partys that caused the leak to occur.

**Comment by turtledude01** [comment]
Id love to see proof of this because nothing I have found officially states this.

**Comment by coderobe** [comment]
> Because Cloudflare operates a large, shared infrastructure an HTTP request to a Cloudflare web site that was vulnerable to this problem could reveal information about an unrelated other Cloudflare site.

[Here's the official blog post, the quote can be found near the end of the post.](https://blog.cloudflare.com/incident-report-on-memory-leak-caused-by-cloudflare-parser-bug/)

**Comment by turtledude01** [comment]
Ive already read that one, doesn't prove anything

**Comment by coderobe** [comment]
The whole blog post goes into detail explaining why, and what exactly happened. It's been published by Cloudflare themselves. Personally i'd say this is proof enough

**Comment by turtledude01** [comment]
Now show me proof that every site listed in this repo was affected.

**Comment by coderobe** [comment]
The key words are `could have` and `possibly`

**Comment by pirate** [comment]
Even sites cloudflare has manually emailed saying they're not affected are not "proven" to be unaffected: https://github.com/pirate/sites-using-cloudflare/issues/87#issuecomment-282372235
