### ISSUE TITLE
Remove 1password based on Twitter for cloudflare and 1password

### ISSUE THREAD

**Issue by mralext20** [pirate/sites-using-cloudflare#13]
https://twitter.com/Cloudflare/status/834940080397529088
https://twitter.com/1Password/status/834933333704359937

**Comment by pirate** [comment]
Just edited the readme.

**Comment by sxlijin** [comment]
This change should be reverted: https://twitter.com/taviso/status/834935095639232513

**Comment by pirate** [comment]
https://twitter.com/1Password/status/835152048341532672
