### ISSUE TITLE
I need maintainers to help, this is too much work

### ISSUE THREAD

**Issue by pirate** [pirate/sites-using-cloudflare#132]
If you or a company you work for are willing to help officially maintain this list, please comment here.

It's getting to be too much work for me to personally confirm every site by hand, and I don't want to rush the job. 

 - if you run a password manager, you can help curate a list of sites you users need to reset passwords on
 - if you run a security consultancy, you can alert your users that they may have services affected
 - if you're a personal security researcher you can help by writing a script that automates removing static sites or DNS-only sites

**Comment by ddymko** [comment]
I am willing to help out the best I can....

**Comment by pirate** [comment]
Paging: @Zenexer @abalabahaha @coderobe @wolever @franciscop @pathmissing @thislooksfun @Xaekai @youngj @ymschaap @ddymko 
I'm willing to make you guys contributors if you're interested, we can agree on some basic criteria needed for removing domains from the list, and close out a lot of these PRs.  I'm also looking to get [security companies involved](https://twitter.com/thesquashSH/status/835222576603545604) in owning this list, since it's too much work for a single maintainer at this point. 

I propose this plan of action:  

1. merge all static site PRs
2. write a simple removal script to remove domains and resort/uniquify the list
3. remove any PRs that have provided ownership verification papertrail, and claim they have never used Cloudflare's proxy during the affected period
4. close PRs for sites using the proxy that have user data with a standard rejection message

**Comment by coderobe** [comment]
Sure, count me in if you want.

**Comment by ddymko** [comment]
count me in as well!

**Comment by abalabahaha** [comment]
@pirate sure thing. Do you have a preferred platform we can communicate on?

**Comment by pirate** [comment]
@abalabahaha irc.freenode.net #sites-using-cloudflare

**Comment by Xaekai** [comment]
I have already ran the script I wrote for domains starting with `0` and `8`

**Comment by ddymko** [comment]
@pirate also is there a specific email address where they can send verification?

**Comment by youngj** [comment]
count me in too

**Comment by pirate** [comment]
@ddymko verifydomain@sweeting.me

**Comment by Zenexer** [comment]
https://keybase.io/zenexer

I'll be on IRC when I get home. Among other things, I may be able to provide some resources, such as hosting and zone files.

**Comment by pirate** [comment]
FYI the policy is now to allow sites that used the proxy with user data to add blog posts regarding cloudflare to the README:

- adafruit.com \[no evidence of data leaked](https://example.com/blog/post-about-cloudflare-leak)

We don't want to remove them from the list because they did use the proxy, but we're letting them indicate that they have addressed the issue in an official announcement.

**Comment by pathmissing** [comment]
You can count me in

**Comment by tonyztan** [comment]
@pirate Glad to help. Count me in. https://keybase.io/tonytan

**Comment by Phineas** [comment]
I'll help out @pirate

**Comment by Zenexer** [comment]
@tonyztan FYI, your DNS and HTTPS Keybase proofs for tonytan98.com are failing.

**Comment by tkachenko** [comment]
Small PHP script to left just domains thats use CloudFlare proxy 
But not very optimal way.. =( 
 
`<?php

$i = 0;
$file = 'sorted_unique_cf.txt';
$f = fopen($file, 'r');


$ipcache = [];

while (false !== ($line = fgets($f))) {
   // echo $line;
    $i++;
    $ip = gethostbyname(trim($line));

    if($ip){
        if(!isset($ipcache[$ip])){
            $w = exec('whois '.$ip.' | grep noc@cloudflare.com');
            if($w){
                $ipcache[$ip] = 1; // its cloudflare proxy
            }else{
                $ipcache[$ip] = 0; // this site doesnt use proxy
            }
        }
       if(isset($ipcache[$ip]) AND $ipcache[$ip])
           echo $line;
    }
}`

**Comment by calnation** [comment]
@pirate and others participating, the list is now also linked to under External links on [Cloudbleed Wikipedia page](https://en.wikipedia.org/wiki/Cloudbleed). Keep up the good work. :thumbsup:

**Comment by pirate** [comment]
@calnation I'm assuming you're calexit on Wikipedia? If so, thanks for helping write the wiki!

**Comment by tycoonlover1359** [comment]
I'm not mentioned here, but if needed, I can still be assisting you guys in helping to get people to provide necessary information to confirm their sites aren't affected, thus can be removed. Would you like this or would you like me to stop and sorta get out of the way? I don't mind either option, whatever you guys decide is fine by me.

**Comment by pirate** [comment]
@tycoonlover1359 thanks for the help so far! I think we have enough committers at the moment, I'll ping you if that changes.
