### ISSUE TITLE
namecheap should not be listed as unaffected

### ISSUE THREAD

**Issue by fletom** [pirate/sites-using-cloudflare#134]
they admit in their [blog post](https://status.namecheap.com/archives/30660) that they were using the Cloudflare proxy, but say "We also have initial confirmation from CloudFlare that we have not been affected."

this is impossible. they are either lying or mistaken.

**Comment by youngj** [comment]
Agreed

**Comment by fletom** [comment]
found a copy of the email they're sending around

![](https://pbs.twimg.com/media/C5cqwQtU4AIEsJk.jpg:large)

Namecheap most likely received this. to the untrained eye, it's telling them they aren't affected. but that's just Cloudflare being tricky and utterly disingenuous. the fact that they couldn't find a domain leak in a third party cache absolutely does not mean it wasn't affected.

**Comment by youngj** [comment]
Reworded "not affected" to "no evidence of compromised data".
