### ISSUE TITLE
Glassdoor

### ISSUE THREAD

**Issue by roguedarkjedi** [pirate/sites-using-cloudflare#139]
Their login popup returns cloudflare headers, I haven't been able to confirm on login as the oauth handshake doesn't go through.

They claim that Cloudflare has told them they weren't affected.

https://twitter.com/Glassdoor/status/835238343822589952

**Comment by youngj** [comment]
Added in e920103e6b330f78b994adba1e908dfe83193a6b . Thanks!

**Comment by coderobe** [comment]
They are likely affected, yeah.
