### ISSUE TITLE
Alphabetical order?

### ISSUE THREAD

**Issue by Adoroam** [pirate/sites-using-cloudflare#14]
You could make the list more human friendly if you alphabetize it. I would suggest just copying the list into a decent text editor and telling it to sort the lines. It's a quick and easy fix, but I feel like it would help a lot of people.

**Comment by pirate** [comment]
The full list is sorted alphabetically, the *Notable* section is sorted based on roughly how important I think it is to change passwords (i.e. money-related sites first).

I can sort the Alexa 10,000 once I get home, I'm about to head out.

**Comment by pirate** [comment]
Alexa 10,000 is now sorted.
