### ISSUE TITLE
Change "not affected"/"no evidence of compromised data"; clarify meaning

### ISSUE THREAD

**Issue by Zenexer** [pirate/sites-using-cloudflare#153]
This note that we've added in parentheses next to some domains is inaccurate.  Even where it says "no evidence of compromised data", it's quite misleading.  We should change these to say something along the lines of "public statement" or "doesn't appear in Google cache".

**Comment by pirate** [comment]
Yeah I like "doesn't appear in search engine caches".  We should edit them manually, some sites actually have no compromised data, such as 1password.

**Comment by Zenexer** [comment]
From what was said on IRC, I don't think "doesn't appear in search engine caches" would be wise/accurate, either.  Cloudflare's messages to customers have only mentioned Google, and allegedly other caching/archiving services have retained information that Google never had (which makes sense).

**Comment by pirate** [comment]
AFAIK from twitter posts they were working with bing, yahoo, and duckduckgo as well, but not 100% that they're all cleared at once.

**Comment by Zenexer** [comment]
Then "several major search engines" might be appropriate, but there's still a difference between clearing caches and querying for leaked data.  We also haven't heard anything about Baidu or Yandex.

**Comment by Zenexer** [comment]
Any objections to this?

> no leaked data found in several search engine caches

**Comment by ddymko** [comment]
I missed this thread @Zenexer - I will update the digital ocean pr to reflect the the more appropriate message
