### ISSUE TITLE
Remove a few domains

### ISSUE THREAD

**Issue by rcombs** [pirate/sites-using-cloudflare#163]
None of these sites receive user information:
- rcombs.me
- analblaze.com
- splatoon.ink
- sakuga.moe
- plex.moe

And these are all static and also some degree of NSFW:
- shiningfingered.moe
- shining-fingered.moe
- ass.moe
- rule34.moe

**Comment by pirate** [comment]
These domains all have logins & signups:

- plex.moe
- sakugabooru.com
- gelbooru.com
- rule34.moe

**Comment by rcombs** [comment]
- plex.moe is just a redirect
- sakuga.moe is just a redirect
- ass.moe is just a redirect
- rule34.moe is… oh, that actually routes, sorry, guess that one's fine.

**Comment by VosAndHowden** [comment]
1Password, while they use Cloudflare, is not vulnerable and probably shouldn't be on this list.

https://blog.agilebits.com/2017/02/23/three-layers-of-encryption-keeps-you-safe-when-ssltls-fails/

**Comment by nikitasius** [comment]
Domains are affected only in case if all data was proxied via Cloudflare. In case if you proxy static AND/OR don't proxy auth forms AND do not use ".example.com" cookies - you not affected.

**Comment by pathmissing** [comment]
@VosAndHowden We are keeping track of sites which might potentially have been affected by CloudBleed, not wether their security may or may not have prevented the leak of data. In the case of 1Password, we added a link to a discussion with more information.

**Comment by jose-oc** [comment]
ankiweb.net recommends to change the password because of this issue. It could be added to the list.

**Comment by pirate** [comment]
I'm closing this issue and others like it.  The list is now archived an I'm not accepting any change requests.  I know this comes as a surprise and may seem unfair but please consider the following:

 - you can link concerned users directly to our [README](https://github.com/pirate/sites-using-cloudflare/blob/master/README.md), which explicitly states the list contains many unaffected sites
 - you can link users to [several](https://www.troyhunt.com/pragmatic-thoughts-on-cloudbleed/) [articles](https://techcrunch.com/2017/02/24/how-to-secure-your-data-after-the-cloudflare-leak/) discussing how minor the leak's impact is
 - our README clearly states the list is not for end-users, and is for technical analysis (the title is also changed from "affected sites" to "Cloudflare DNS users")
 - I will be intentionally breaking search tools shortly by moving the txt file to a new location (no more browser extensions for searching the list)

If you have a specific objection or unrelated issue you want resolved, you can contact me via twitter DM.  Thanks for your understanding.
