### ISSUE TITLE
Turn urls into links, so user can quickly see which one from the list he were visiting

### ISSUE THREAD

**Issue by dchaplinsky** [pirate/sites-using-cloudflare#166]
**Please, do not create duplicate issues**

### DISCLAIMER:
This list contains *all* domains that use CloudFlare DNS, not just the CloudFlare SSL proxy (the affected service that leaked data).
It's a broad sweeping list that includes everything.  Just because a domain is on the list does not mean the site is compromised.
This list will be narrowed down to the affected domains as we get more information.

### HOW TO REMOVE YOUR SITE
1. Verify the site is static and contains no user or sensitive data (I will remove it immediately once I confirm)  

OR  

1. Verify ownership, send me an email from @yourdomain.com, post a random nonce on the domain, or provide keybase proof
2. Verify you did not use the Cloudflare proxy service during the affected period 

(this is obviously not proof that you weren't affected, but this serves as a paper trail for accountability reasons, in case
someone wants to dispute that you were affected, we have an employee/owner of the domain who can be held accountable)

I will not remove sites that contain user data and are returning `server:cloudflare-nginx` in response headers, since they may have been affected.
You're welcome to submit a PR to include a link to a blog post for your users, e.g.:

- example.com \[no evidence of data leaked](https://example.com/blog/cloudflare-data-leak)

**Comment by nikitasius** [comment]
> HOW TO REMOVE YOUR SITE

Sound nice. But if domain use Cloudflare DNS it **doesn't mean** what domain was affected.

I will explain:
there is non-proxified domain **example.com** - what provide access to backend and there is **static.example.com** what proxified via Cloudflare.

Domain **example.com** use cookies with `example.com`, not with `.example.com` (dot-example-dot-com).

In such case we have a domain example.com parked on Cloudflare's DNS using CF to proxy static content and only. As most of domains in your list (i fond my domains and my clients in).

So this list cannot be used as a 100% proof called "Leaked domains". Just a simple statistics and not more.

**Comment by Phineas** [comment]
@nikitasius I think the issue poster means turning the URLs in the README, etc to http url redirects

**Comment by Phineas** [comment]
Added -> b7a7e78fbe37a9d3af1c06225ad912f70bbf698e Thanks!
