### ISSUE TITLE
Remove: lukweb.de, rgts.ga, twitch-tools.ga (static)

### ISSUE THREAD

**Issue by LukBukkit** [pirate/sites-using-cloudflare#183]
Hello,

can you please remove my domains:
* lukweb.de
* rgts.ga
* twitch-tools.ga

You find me on [Keybase](https://keybase.io/lukbukkit), there are all three domains proved.
Thank you 😃

**Comment by pirate** [comment]
@LukBukkit your sites have been removed 👍.

**Comment by LukBukkit** [comment]
Thank you
