### ISSUE TITLE
Dynalist and Teachable are using CloudFlare

### ISSUE THREAD

**Issue by grub-basket** [pirate/sites-using-cloudflare#191]
I have no idea how to do a pull request, so I apologize in advance for opening an issue for this. 

[Dynalist.io](dynalist.io) (they said that they were most probably not affected, in an email by CloudFlare)
[Teachable.com](teachable.com) (formerly Fedora) - I only [checked](whoishostingthis.com) who their host was.

**Comment by pirate** [comment]
I'm closing this issue and others like it.  The list is now archived an I'm not accepting any change requests.  I know this comes as a surprise and may seem unfair but please consider the following:

 - you can link concerned users directly to our [README](https://github.com/pirate/sites-using-cloudflare/blob/master/README.md), which explicitly states the list contains many unaffected sites
 - you can link users to [several](https://www.troyhunt.com/pragmatic-thoughts-on-cloudbleed/) [articles](https://techcrunch.com/2017/02/24/how-to-secure-your-data-after-the-cloudflare-leak/) discussing how minor the leak's impact is
 - our README clearly states the list is not for end-users, and is for technical analysis (the title is also changed from "affected sites" to "Cloudflare DNS users")
 - I will be intentionally breaking search tools shortly by moving the txt file to a new location (no more browser extensions for searching the list)

If you have a specific objection or unrelated issue you want resolved, you can contact me via twitter DM.  Thanks for your understanding.
