### ISSUE TITLE
Some sites to add to the notable domains?

### ISSUE THREAD

**Issue by TobiX** [pirate/sites-using-cloudflare#195]
Maybe add the following sites to the list of notable domains, since they might be a bit more "impactful"?

- chocolatey.org (Software distribution, API keys)
- inwx.de (German domain provider)
- privatevpn.com (VPN provider)
- flattr.com (Community payment)

Some smaller game bundle sites besides Humble Bundle also use CloudFlare, which raises the question if it would be a good idea to add "shopping" sites to the "notable" list or if that is an amount of curation a small community-team can't handle...

- bundlestars.com
- dailyindiegame.com
- getgamesgo.com
- groupees.com (Probably only DNS)
- indiegamestand.com

Oh, and onlinekeystore.com ;)

**Comment by Phineas** [comment]
I haven't heard of any of the websites here - notable sites are meant to be "popular sites" really, not sites which might have a high impact rate.

**Comment by coderobe** [comment]
the only sites i've ever heard of in that list would be chocolatey & flattr

flattr might be worth to add because it's a payment system

**Comment by pirate** [comment]
Sorry guys, archiving this list.  Really appreciate all the contributions though!
