### ISSUE TITLE
Remove: nightcube.net (Static) (No User Data Stored)

### ISSUE THREAD

**Issue by GatheringRays** [pirate/sites-using-cloudflare#203]
[nightcube.net](https://www.nightcube.net) stores no personally identifiable information and does not have a single database that could've been leaked either way. This site is in fact cached by Cloudflare; however, no user data (except for the standard log files for recording user's actions on the site) is stored, which means our site has not been affected in any way by CloudBleed. We don't even have a log-in page for data to be processed anyways, and most of our content is static content.

**Comment by Phineas** [comment]
:thinking: https://www.nightcube.net/phpmyadmin

**Comment by GatheringRays** [comment]
MySQL was used in a previous version of NightCube used 2 years ago on a different domain, which is why the directory for PHPmyAdmin still exists, but is has since been erased and wiped entirely. We have verified that no data exists here and that the SQL server was completely shut down and wiped clean. All that remained was the PHPmyAdmin directory, which cannot be removed without causing issues with our servers.

**Comment by pirate** [comment]
I'm closing this issue and others like it.  The list is now archived an I'm not accepting any change requests.  I know this comes as a surprise and may seem unfair but please consider the following:

 - you can link concerned users directly to our [README](https://github.com/pirate/sites-using-cloudflare/blob/master/README.md), which explicitly states the list contains many unaffected sites
 - you can link users to [several](https://www.troyhunt.com/pragmatic-thoughts-on-cloudbleed/) [articles](https://techcrunch.com/2017/02/24/how-to-secure-your-data-after-the-cloudflare-leak/) discussing how minor the leak's impact is
 - our README clearly states the list is not for end-users, and is for technical analysis (the title is also changed from "affected sites" to "Cloudflare DNS users")
 - I will be intentionally breaking search tools shortly by moving the txt file to a new location (no more browser extensions for searching the list)

If you have a specific objection or unrelated issue you want resolved, you can contact me via twitter DM.  Thanks for your understanding.
