### ISSUE TITLE
Removal of foxdev.co, revthefox.co.uk, pste.pw, foxbnc.co.uk and notoriousdev.com

### ISSUE THREAD

**Issue by TheReverend403** [pirate/sites-using-cloudflare#205]
None of my domains have used CloudFlare's CDN since Let's Encrypt was in private beta, so it is not possible for them to have been affected.

https://keybase.io/thereverend403/ and I can send an email from @notoriousdev.com upon request.

**Comment by Phineas** [comment]
Could you add notoriousdev.com to your Keybase?

**Comment by coderobe** [comment]
@Phineas notoriousdev.com seems like a static page, i don't think we need additional confirmation for that

**Comment by pirate** [comment]
I'm closing this issue and others like it.  The list is now archived an I'm not accepting any change requests.  I know this comes as a surprise and may seem unfair but please consider the following:

 - you can link concerned users directly to our [README](https://github.com/pirate/sites-using-cloudflare/blob/master/README.md), which explicitly states the list contains many unaffected sites
 - you can link users to [several](https://www.troyhunt.com/pragmatic-thoughts-on-cloudbleed/) [articles](https://techcrunch.com/2017/02/24/how-to-secure-your-data-after-the-cloudflare-leak/) discussing how minor the leak's impact is
 - our README clearly states the list is not for end-users, and is for technical analysis (the title is also changed from "affected sites" to "Cloudflare DNS users")
 - I will be intentionally breaking search tools shortly by moving the txt file to a new location (no more browser extensions for searching the list)

If you have a specific objection or unrelated issue you want resolved, you can contact me via twitter DM.  Thanks for your understanding.
