### ISSUE TITLE
Remove ganking.club, jennig.es, gunfighterj.com, hogs.space, hogscollective.space

### ISSUE THREAD

**Issue by GunfighterJ** [pirate/sites-using-cloudflare#206]
Well, guilty til proven innocent I guess.

Below are links to a static text document on each of the above domains proving my ownership and request for removal. They will link to this issue and will be updated within a couple minutes after being submitted with the proper link.

The domains listed were using cloudflare only for DNS except for gunfighterj.com which is a static site with no user content.

List of sites:
https://ganking.club/cloudflare.txt
https://jennig.es/cloudflare.txt
https://gunfighterj.com/cloudflare.txt
https://tools.hogs.space/cloudflare.txt (hogs.space redirects to hogscollective.space by default)
https://hogscollective.space/cloudflare.txt

**Comment by Phineas** [comment]
Do you have Keybase proof?

**Comment by Zenexer** [comment]
@Phineas I think those text files should be sufficient, no?

**Comment by GunfighterJ** [comment]
I added my github profile to each text file.

**Comment by coderobe** [comment]
@GunfighterJ No, keybase provides a cryptographic proof as well

**Comment by GunfighterJ** [comment]
Cryptographic proof of what?

**Comment by coderobe** [comment]
Although the domain(s) in question don't seem like something that needs extra validation, so i'd let it pass

**Comment by TheReverend403** [comment]
What do you need a cryptographic proof for? The domain itself links to his Github profile, it's not like that could happen if he didn't own it.

**Comment by coderobe** [comment]
@GunfighterJ Proof of ownership. The text files should be sufficient in your case though.

**Comment by GunfighterJ** [comment]
Any update? The proof is there, I would like my sites removed please.

**Comment by MeltedLux** [comment]
:^)

**Comment by TheReverend403** [comment]
This list is honestly the worst form of cancer I've personally ever seen on the internet. Guilty until proven innocent, except even when proven innocent, you're at the mercy of collaborators who clearly can't be bothered to even maintain their shitty list anymore.

![guilty m8](https://cdn.vectorstock.com/i/thumb-large/13/23/9521323.jpg)

**Comment by coderobe** [comment]
@TheReverend403 You should've read the ReadMe & the repo name. This is not a list of "hacked sites"™, it's a list of sites using Cloudflare *during the affected time period*.

**Comment by coderobe** [comment]
@GunfighterJ Can you post a PR addressing this issue? I'll merge it.

**Comment by MeltedLux** [comment]
For a list of sites using Cloudflare during the time their _nginx_ was affected there's a whole lot of incorrect entries :^)

**Comment by pirate** [comment]
@coderobe fyi text file is sufficient proof of ownership, and proof of ownership isn't needed for static sites (it's only for paper trail for large sites).

**Comment by pirate** [comment]
I'm closing this issue and others like it.  The list is now archived an I'm not accepting any change requests.  I know this comes as a surprise and may seem unfair but please consider the following:

 - you can link concerned users directly to our [README](https://github.com/pirate/sites-using-cloudflare/blob/master/README.md), which explicitly states the list contains many unaffected sites
 - you can link users to [several](https://www.troyhunt.com/pragmatic-thoughts-on-cloudbleed/) [articles](https://techcrunch.com/2017/02/24/how-to-secure-your-data-after-the-cloudflare-leak/) discussing how minor the leak's impact is
 - our README clearly states the list is not for end-users, and is for technical analysis (the title is also changed from "affected sites" to "Cloudflare DNS users")
 - I will be intentionally breaking search tools shortly by moving the txt file to a new location (no more browser extensions for searching the list)

If you have a specific objection or unrelated issue you want resolved, you can contact me via twitter DM.  Thanks for your understanding.

**Comment by GunfighterJ** [comment]
Thank you. I can agree to this.
