### ISSUE TITLE
remove nya.is

### ISSUE THREAD

**Issue by neko** [pirate/sites-using-cloudflare#207]
Nya.is does not use the service in a way that would make it vulnerable to the data leaks; we only use Cloudflare's proxy for static content.

Proof that I own the domain can kinda be found on [my keybase](https://keybase.io/senpai).

**Comment by Phineas** [comment]
But you have a login/register page on the site?

**Comment by neko** [comment]
> **_we only use Cloudflare's proxy for static content._**

**Comment by neko** [comment]
what proof do you need? literally ping nya.is and see that it returns a trabia IP, not a cloudflare IP.

🤔

**Comment by neko** [comment]
as for proof of identity, i linked to my keybase in the OP

![wat](https://u.nya.is/hrkfxe.png)
that's a real thonker right there
