### ISSUE TITLE
Remove: adcanvas.com. No sensitive data was stored over CDN.

### ISSUE THREAD

**Issue by erikCurlify** [pirate/sites-using-cloudflare#208]
**Please, do not create duplicate issues**

### DISCLAIMER:
This list contains *all* domains that use CloudFlare DNS, not just the CloudFlare SSL proxy (the affected service that leaked data).
It's a broad sweeping list that includes everything.  Just because a domain is on the list does not mean the site is compromised.
This list will be narrowed down to the affected domains as we get more information.

### HOW TO REMOVE YOUR SITE
1. Verify the site is static and contains no user or sensitive data (I will remove it immediately once I confirm)  

OR  

1. Verify ownership, send me an email from @yourdomain.com, post a random nonce on the domain, or provide keybase proof
2. Verify you did not use the Cloudflare proxy service during the affected period 

(this is obviously not proof that you weren't affected, but this serves as a paper trail for accountability reasons, in case
someone wants to dispute that you were affected, we have an employee/owner of the domain who can be held accountable)

I will not remove sites that contain user data and are returning `server:cloudflare-nginx` in response headers, since they may have been affected.
You're welcome to submit a PR to include a link to a blog post for your users, e.g.:

- example.com \[no evidence of data leaked](https://example.com/blog/cloudflare-data-leak)

**Comment by coderobe** [comment]
The issue content exists for a reason. Please give more details. Did you use the CDN at all? Affected subdomains? The current www. site does not use CF as proxy.

**Comment by pirate** [comment]
I'm closing this issue and others like it.  The list is now archived an I'm not accepting any change requests.  I know this comes as a surprise and may seem unfair but please consider the following:

 - you can link concerned users directly to our [README](https://github.com/pirate/sites-using-cloudflare/blob/master/README.md), which explicitly states the list contains many unaffected sites
 - you can link users to [several](https://www.troyhunt.com/pragmatic-thoughts-on-cloudbleed/) [articles](https://techcrunch.com/2017/02/24/how-to-secure-your-data-after-the-cloudflare-leak/) discussing how minor the leak's impact is
 - our README clearly states the list is not for end-users, and is for technical analysis (the title is also changed from "affected sites" to "Cloudflare DNS users")
 - I will be intentionally breaking search tools shortly by moving the txt file to a new location (no more browser extensions for searching the list)

If you have a specific objection or unrelated issue you want resolved, you can contact me via twitter DM.  Thanks for your understanding.
