### ISSUE TITLE
stackoverflow not affected

### ISSUE THREAD

**Issue by alienth** [pirate/sites-using-cloudflare#21]
Per CloudFlare's report, earliest that a site could have been affected was 2016-09-22. I moved StackOverflow and related sites off of CloudFlare in June and July of 2016. As such, not possibly affected by this issue.

**Comment by kn00tcn** [comment]
i saw blip.tv in the list, but blip was shut down & it redirects to maker, sounds like the same situation

**Comment by pirate** [comment]
Great! @alienth can you email me at verifystackoverflow@sweeting.me from a @stackoverflow.com email to confirm?

**Comment by pirate** [comment]
Done: https://github.com/pirate/sites-using-cloudflare/commit/b637f6f51509ff0a9ac4567d79d5aa8588e9e9fd
I'd prefer to move it to the bottom with a (not affected) flag like the others, let me know if that's an issue.

**Comment by NickCraver** [comment]
We've still seen confusion over this - can  you please remove us from the list as we were in no way involved?

**Comment by pirate** [comment]
@NickCraver done: 4f0f433
