### ISSUE TITLE
Removal of hatethe.uk, hasabig.wang, hasalittle.wang, melted.me, melted.pw, invictusmc.uk, invictusmc.us

### ISSUE THREAD

**Issue by MeltedLux** [pirate/sites-using-cloudflare#212]
None of these domains have ever used Cloudflare as a CDN service only as DNS they were not affected by this vulnerability.

https://keybase.io/meltedlux

You are also listing mitigation.pw & mitigation.tech which have expired on the 25/02/2017 and were also only using Cloudflare as DNS. [Namecheap Proof](https://i.hatethe.uk/bnettNrgrnAT.png)

These domains are also listed on my keybase sigchain as revoked due to the expiration:
[80](https://keybase.io/meltedlux/sigchain#b695d4a21007236864134a3648232d4ad19b41157fff49bda63a9be2c584d1290f)
[81](https://keybase.io/meltedlux/sigchain#4bccc3456a6717041f53a2b0a7e1ce750c032d7b9ebb90b264060bd39f3e3d700f)

**Comment by coderobe** [comment]
invictusmc.uk is not static, so we'll have to confirm your identity. Please send a mail to spam@rob1nn.pw (me) with an @invictusmc.uk address referencing this issue, confirming you did not use CF as a proxy during the affected time period.

**Comment by MeltedLux** [comment]
I have done so.

**Comment by coderobe** [comment]
I received the mail, it doesn't seem to be signed by DKIM or PGP.
I was able to verify that the mail likely came from the MX authority for invictusmc.uk, though. MX for invictusmc.uk is mail.melted.me, which points to bifrost.melted.me - the host my server received the mail from.

@MeltedLux I will remove your domains.
