### ISSUE TITLE
Add affected domains used by some iOS apps

### ISSUE THREAD

**Issue by dweinstein** [pirate/sites-using-cloudflare#22]
these haven't been all manually confirmed but was based on the connections made by each app during dynamic analysis https://gist.github.com/dweinstein/a30f5814dde36425de7bef4168469ac4

**Comment by pirate** [comment]
Swamped with messages right now.  Feel free to add these to the zipped file, run `uniq | sort` and submit a PR, otherwise I'll try and add these in a bit when I have time.

**Comment by pirate** [comment]
Linked to the file, since they aren't all domains https://github.com/pirate/sites-using-cloudflare/commit/d50488031aeed966a455b76f2b30114080b9b371
