### ISSUE TITLE
github itself?

### ISSUE THREAD

**Issue by broxp** [pirate/sites-using-cloudflare#223]
Quick question.

github.se is listed in your file, and also is positive on [doesitusecloudflare.com](http://www.doesitusecloudflare.com/?url=github.es).

Interestingly it redirects to https://github.com/sejas, which is not positive ([doesitusecloudflare.com/?url=github.com%2Fsejas](http://www.doesitusecloudflare.com/?url=github.com%2Fsejas))

So, is any part of github subject to cloudbleed or is it just this directing site?

**Comment by pirate** [comment]
Github.es is a personal site, and not affilieated with github.com (which was not affected).
