### ISSUE TITLE
remove besv.net 10101.info

### ISSUE THREAD

**Issue by s860304** [pirate/sites-using-cloudflare#227]
besv.net just use Cloudflare DNS
use CDN before 2016/08/01

http://server9.rscott.org/tools/lookup.htm?domain=besv.net&date=20160731
http://server9.rscott.org/tools/lookup.htm?domain=besv.net&date=20160801
http://server9.rscott.org/tools/lookup.htm?domain=besv.net&date=20160901
(No history at October)
http://server9.rscott.org/tools/lookup.htm?domain=besv.net&date=20161101
http://server9.rscott.org/tools/lookup.htm?domain=besv.net&date=20161201
http://server9.rscott.org/tools/lookup.htm?domain=besv.net&date=20170101

10101.info just a static website

**Comment by pirate** [comment]
I'm closing this issue and others like it.  The list is now archived an I'm not accepting any change requests.  I know this comes as a surprise and may seem unfair but please consider the following:

 - you can link concerned users directly to our [README](https://github.com/pirate/sites-using-cloudflare/blob/master/README.md), which explicitly states the list contains many unaffected sites
 - you can link users to [several](https://www.troyhunt.com/pragmatic-thoughts-on-cloudbleed/) [articles](https://techcrunch.com/2017/02/24/how-to-secure-your-data-after-the-cloudflare-leak/) discussing how minor the leak's impact is
 - our README clearly states the list is not for end-users, and is for technical analysis (the title is also changed from "affected sites" to "Cloudflare DNS users")
 - I will be intentionally breaking search tools shortly by moving the txt file to a new location (no more browser extensions for searching the list)

If you have a specific objection or unrelated issue you want resolved, you can contact me via twitter DM.  Thanks for your understanding.
