### ISSUE TITLE
Remove my site

### ISSUE THREAD

**Issue by turtledude01** [pirate/sites-using-cloudflare#24]
The site 'turtle-mc.org' is owned and operated by me and is so small and unused that the chance of it being affected is 1 in literally 10 trillion so please remove it from your zip file.

**Comment by turtledude01** [comment]
theres another site aswell - codywentz.com is my friends site that is literally never online and when it is it isnt using the affected things... You really need to clean up your list and stop spreading false information NOW.  The affected sites is less than 200

**Comment by turtledude01** [comment]
OOH and another site: radicaldelta.org (Also owned by me) Seriously im tired of this, get your crap straight... Noone needs a list of EVERY SITE RUN THROUGH CLOUDFLARE.

**Comment by basisbit** [comment]
this is not even a list of every site running through cloudflare. Websites which only use cloudflare dns are also listed even if they don't run through cloudflare.

**Comment by turtledude01** [comment]
This is just a bs list then right? Im kind of tired of people screaming at me in multiple discord/irc servers saying that Im an idiot for thinking My tiny site wasnt affected

**Comment by kn00tcn** [comment]
what does it even matter if your site doesnt have user logins? now you'll get new visitors from those that open this thread

people are screaming at you? either there's something valuable or you're not as tiny or they are dumb

**Comment by turtledude01** [comment]
I'm exaggerating but it is really annoying having people tell me that "no no no your sites on the list it MUST be affected"

**Comment by basisbit** [comment]
also see #17 . that should make this less of a problem.

**Comment by turtledude01** [comment]
Ah yes, great idea there

**Comment by pirate** [comment]
@turtledude01 I can understand your frustration, getting put on a list like this sucks because it makes users who don't understand the issue think something is your fault.
Unfortunately it would take me days to scrape and manually confirm that all these sites are using the SSL proxy, so I started with the broad DNS scrape and we can narrow it down from there.
See https://github.com/pirate/sites-using-cloudflare/issues/19

**Comment by pirate** [comment]
I'll be removing sites one-by-one as they confirm they aren't affected.

**Comment by turtledude01** [comment]
Then please remote turtle-mc.org, radicaldelta.org, and codywentz.com as I own 2 and my friend owns the other.

**Comment by turtledude01** [comment]
If you get the unzipped file uploaded soon enough I wont worry about having you remove my sites and ill take care of it myself in a pr

**Comment by CubeBag** [comment]
Even if there is a 0.001% chance it was affected, the site still shouldn't be removed unless there is solid proof that it was never vulnerable. Winning the lottery is unlikely but possible, and it's better (in my opinion) to have a false positive than a false negative.

**Comment by turtledude01** [comment]
In my 'opinion' a site that gets maybe 1 visitor per 12 hours does not need to be on this list as the usefullness of it being on this list is NONE

**Comment by pirate** [comment]
Sorry @turtledude01 I'm going to have to disagree with you there.  If your site used the Cloudflare TLS proxy at any time during the affected period I think it should stay on the list.  If you think the current wording will seriously affect your reputation, I invite you to contribute to making the disclaimer clearer over in https://github.com/pirate/sites-using-cloudflare/issues/19

**Comment by turtledude01** [comment]
Wow, even if i can 100% say my sites have not been affected by this you refuse to remove them? freaking great

**Comment by turtledude01** [comment]
I believe that if somone requests for their site to be removed it should be removed

**Comment by pirate** [comment]
@turtledude01 I'm happy to remove static sites with no personal data, but sites that have possibly exposed personal data need to stay on the list.

**Comment by me4502** [comment]
Probs me4502.com as well. No personal data has been stored or collected for a fairly long time now.

**Comment by pirate** [comment]
@me4502 submit PRs for the static sites if you haven't already and I'll approve 'em.
