### ISSUE TITLE
Remove sites not affected by this vuln

### ISSUE THREAD

**Issue by coderobe** [pirate/sites-using-cloudflare#28]
Several (currently listed) sites, including `coderobe.net` and `rob1nn.pw` which [i'm the provable owner of](https://keybase.io/coderobe) were not affected by this vulnerability. This should:
- Be stated in readme.md
OR:
- Removed from the zip entirely

Now that this repository is making the news, this could potentially hurt the reputation of many sites.

**Comment by coderobe** [comment]
Creating PRs for this is not very useful, because the file is zipped - which makes merging multiple PRs nearly impossible / an infeasible thing to do. I'd suggest a switch to keeping the file(s) uncompressed, potentially split into multiple files.

**Comment by pirate** [comment]
@coderobe good ideas on both count. I'll be updating the README shortly and uploading the unzipped file.

**Comment by pirate** [comment]
I've added a disclaimer to the README: https://github.com/pirate/sites-using-cloudflare#full-list
The text file is currently uploading (it's huge), I'll edit this comment with a link to it once it's completed.

**Comment by pirate** [comment]
@coderobe happy to remove your sites as they're personal and don't appear to have any user data.  Just submit a PR and I'll recompress the zip for you.

**Comment by coderobe** [comment]
Here's the PR btw https://github.com/pirate/sites-using-cloudflare/pull/117
