### ISSUE TITLE
Procedure for getting your domains removed

### ISSUE THREAD

**Issue by tycoonlover1359** [pirate/sites-using-cloudflare#29]
**Note: I am not an official contributor of this repository nor am I affiliated with the owner of it in any way. I am simply just a person attempting to help the owner of the repository**

I am speaking based on what I have seen others comment on the issues of this list, and I will provide answer I've tried gathering based on what @pirate has stated in other issues and the main page. **I will update this list as time goes on as I do my best to assist the owner of the repository to the best of my ability. If you feel a question or issue should be added, comment below and I will consider it based on other comments people have added on other issues and what @pirate has stated before.**

1. The list is incorrect. It involves sites that don't use / weren't / aren't affected by this.
A: These sites, as the disclaimer on the front page states, have **possibly** been affected by this. Until these sites are confirmed as unaffected, the site will remain on the list as a precaution.

2. My site is not affected. Please remove it from the list.
A: Please provide proof that your site in question has not been affected by #cloudbleed. If you need further instruction on how to do this, ask Pirate, the owner of this repository, for assistance.

**Comment by pirate** [comment]
Thanks for the help! I've added a disclaimer to the readme that should help alleviate this issue: https://github.com/pirate/sites-using-cloudflare#full-list

If anyone wants to propose different wording, please submit a PR.

**Comment by pirate** [comment]
I'm only removing sites that are provably static content (e.g. github pages), contain no user data, or never used cloudflare during the affected period.

For domain verification I need either a DKIM signed email from the domain, a keybase verification, or a file uploaded with a random number that I'll give you.

Open a PR to have a site removed, and put your proof in the description.

**Comment by pirate** [comment]
I think there's enough documentation on how to submit requests, closing this for now.
