### ISSUE TITLE
Explain how to 'prove' my sites were not affected

### ISSUE THREAD

**Issue by turtledude01** [pirate/sites-using-cloudflare#35]

**Comment by pirate** [comment]
Can you list the domains you want removed, and whether or not they contain user data.
I will check if they are using the SSL proxy.

If your site is just a static site or has no personal user data, I'm happy to remove it.

**Comment by turtledude01** [comment]
radicaldelta.org has only 1 account which is mine so remove it.  Friends site 'codywentz.com' has not had user accounds ever, tho I cant prove this... turtle-mc.org has a couple of user accounts running through joomla

**Comment by pirate** [comment]
radicaldelta.org and turtle-mc.org are both returning `server:cloudflare-nginx`, codywentz.com is down so I cant check it.

**Comment by turtledude01** [comment]
like i said, radicaldelta.org has ONLY 1 account which is MY OWN ACCOUNT and codywentz.com is barely ever up, doesnt use cloudflare for anything other than dns, and doesnt have user accounts.  turtle-mc.org is the only one that could have 'potentially' (1 in ~2 trillion chance) have leaked information.

**Comment by coderobe** [comment]
describing the underlying tech stack would give some insight as well.

turtle-mc was likely affected, because it's using the cloudflare reverse proxy and runs joomla, which provides an account system

**Comment by XhmikosR** [comment]
@pirate: can you remove plain static sites as well? Like https://github.com/XhmikosR/xhmikosr.io/tree/gh-pages

**Comment by turtledude01** [comment]
And if you refuse to remove turtle-mc.org or believe that it 100% was compromised then i would be happy to force a reset on all user passwords, which will send the users an email with a link to reset their password.  I refuse to 'prove' that this was done as that would be a security threat in itself

**Comment by coderobe** [comment]
Whilst there is no reason to believe that low-profile sites were affected, it's entirely possible - because the cf servers apparently also leaked unrelated data if it happened to be on the same node as a different website

This means that if your server was served on the same node as a high-profile site, and a login happened on your site during the last few months, it's completely possible that sensitive data has leaked through other pages

**Comment by turtledude01** [comment]
I just sent an email to every user of turtle-mc.org explaining that their account may have been leaked and I might be resetting passwords.  this better be enough to have it removed as its all i can do

**Comment by SpEcHiDe** [comment]
Can you remove shrimadhavuk.me also from the list, because it is just a static site hosted by GitLab Pages built using Jekyll? I do not think I collect any user-data on the given site.

**Comment by pirate** [comment]
@SpEcHiDe please submit a PR, I'll approve it if it's a static page.

@turtledude01 I'm closing this issue, as I said earlier, I'm only removing sites that are provably static content, contain no user data, or never used cloudflare during the affected period.
