### ISSUE TITLE
Tools for easily searching the list

### ISSUE THREAD

**Issue by thislooksfun** [pirate/sites-using-cloudflare#37]
It might be nice to have a searchable HTML site for the non-programmers that don't know how to use Github/grep. I am willing to throw one together early tomorrow afternoon (~13hrs from now), but if anyone wants to do it sooner, I wouldn't complain.

EDIT: Here's the list so far:
http://www.doesitusecloudflare.com/ (doesn't search the historical list, it's just current sites)
https://chrome.google.com/webstore/detail/cloudbleed-bookmark-check/egoobjhmbpflgogbgbihhdeibdfnedii - chrome plugin
http://cloudflarelistcheck.abal.moe/
https://talepicker.com/cloudbleed/
https://cloudbleed.ak5s.com/
https://thislooksfun.github.io/cloudbleed-search/ (mine - fully browser based)
http://pickarsch.xyz/
https://cloudbleedcheck.com/
https://github.com/Eonasdan/LeakyCloudChecker/ - windows app
https://bleed.cloud/index.html
https://chrome.google.com/webstore/detail/cloudbleed/gmbmbodfgolnnfhfanhjeodfambaoklj - chrome plugin
https://addons.mozilla.org/en-US/firefox/addon/cloudbleed/ - Firefox plugin
https://github.com/mikemrm/CloudFlare-HistoryChecker - Chrome / Firefox history checker

**Comment by pirate** [comment]
I was planning on setting this up at some point, but if anyone else wants to toss one together before me, go for it.

**Comment by abalabahaha** [comment]
I might be taking a stab at this in a few hours

**Comment by coderobe** [comment]
You can open the txt in a browser tab and ctrl-f, there is no need for a website IMO  

If there's gonna be one, i suggest keeping that in it's own repository though

**Comment by abalabahaha** [comment]
@coderobe not everyone wants to load a 68.4MB txt to search a single string

**Comment by tycoonlover1359** [comment]
I would definitely agree with this. I'd make one myself, however I only know EXTREMELY basic HTML.

@coderobe A site for this would look a lot better, and be more user friendly.

**Comment by thislooksfun** [comment]
Yes, but people might not know that. Since this affects more than just us people familiar with GitHub and even that web browsers have a search function, it would be nice.

I would do it now, but I unfortunately really need to get to bed so I can actually function in the morning. If nobody else has taken it up by the time I'm free I will take a stab at it.

**Comment by coderobe** [comment]
I agree. Still, keeping it in a different repository would be beneficial for easy management / version control of the "database"

**Comment by abalabahaha** [comment]
Agreed, since the site code should be mostly static after initial development. Having a link here directing to the other repo/site is enough.

**Comment by basisbit** [comment]
maybe putting cloudflare as cache in between github.io and that website would be a fun idea - now that they fixed the actual issue.

**Comment by pirate** [comment]
http://www.doesitusecloudflare.com/

**Comment by franciscop** [comment]
Ouch, didn't see this issue and ended up doing one myself with the list from this repository. It's open source so you can actually switch it for any text dataset of your own. Will publish it when it gets deployed, which should be soon.

**Comment by franciscop** [comment]
Never mind, it uses 590MB of RAM and I'm not going to pay hundreds of dollars for a Heroku Professional Dyno, the code is in https://github.com/franciscop/cloudbleed

**Comment by rickdmer** [comment]
Not exactly what was requested, but I created a Chrome extension that searches your bookmarks for sites that use Cloudflare: https://chrome.google.com/webstore/detail/cloudbleed-bookmark-check/egoobjhmbpflgogbgbihhdeibdfnedii

**Comment by abalabahaha** [comment]
Made a very barebones list checker on my site for now, will improve on it when I get the time

**Comment by BhawaniGarg** [comment]
Here is a little tool from which you can search: https://talepicker.com/cloudbleed/

**Comment by franciscop** [comment]
BTW if anyone wants http://cloudbleed.site/ I'll point the DNS to their project or transfer it

**Comment by thislooksfun** [comment]
I'm starting work now on a simple search. Progress will be over at https://github.com/thislooksfun/cloudbleed-search , contributions are welcome.

**Comment by pathmissing** [comment]
I too made a little tool: https://cloudbleed.ak5s.com/

**Comment by pathmissing** [comment]
As already discussed in the IRC, I propose to use @abalabahaha's site and link it in the readme so it is easy to find for everyone.

**Comment by thislooksfun** [comment]
Mine is coming along well. Will post initial version soon.

Related question: would it be possible to maintain some way to see which have been confirmed affected/unaffected? (like an `[affected]` / `[unaffected]` tag after the url in the list for example?

**Comment by Empty2k12** [comment]
I have created a simple Python webserver that uses a Redis cache for high speed domain lookups. Might be useful for anyone needing to check a ton of domains: https://github.com/Empty2k12/CloudBleedInfoServer

**Comment by thislooksfun** [comment]
Ok, first draft of my search is live: https://thislooksfun.github.io/cloudbleed-search/
It's fully browser based at the moment, so it is slow. If anyone wants to put work together to make a faster filter or move filtering to the backend, let me know in a [new issue](https://github.com/thislooksfun/cloudbleed-search/issues)

**Comment by Zenexer** [comment]
@thislooksfun Returning 404 for https://thislooksfun.github.io/cloudbleed-search/sorted_unique_cf.txt

**Comment by thislooksfun** [comment]
Aw crap, one sec...

**Comment by haxhxm** [comment]
I can help set up a website on a webserver

**Comment by MiningPickaxe** [comment]
Whoops, just woke up to see, that a lot of people already did those websites xD
I also created a webpage. It is based on a Node.js server and updates the database every 30min. For faster access times, I cached the whole file. http://pickarsch.xyz

**Comment by ahmadawais** [comment]
C'mon guys! Command line for the win! MacOS comes with `curl` installed. Just open your terminal and write the following command.

```bash
curl -Ls https://git.io/vyT0W | grep -x 'domain.com'
```
Where `domain.com` is what you should change. It will download the file if it outputs your domain name then that means your site might be affected. 

BTW to close the search you can use <kbd>CTRL</kbd> + <kbd>C</kbd>.

**Comment by pathmissing** [comment]
@ahmadawais The average user does not know what a command line is and how to use it. That's why this thread exists.

**Comment by sahal2080** [comment]
Stumbled upon this https://cloudbleedcheck.com

**Comment by Eonasdan** [comment]
Made a windows app that will scan through your Google history against the list. https://github.com/Eonasdan/LeakyCloudChecker/tree/master. Can be downloaded from https://rink.hockeyapp.net/apps/d25274d5cd434dfabf22ff97782267d1/

**Comment by Phineas** [comment]
You can also use this if you <3 Golang - https://github.com/Phineas/cloudbleed-search to copy the code into your own Go project, or anything.

**Comment by sahal2080** [comment]
@pirate et all can someone enable the wiki on this repo and add all the links of tools related there? Should be done following the commandment: though shalt do the Awesome list for thyself first!

Oh and add this site there too: https://bleed.cloud/index.html

**Comment by EmmanuelMess** [comment]
@pathmissing https://cloudbleed.ak5s.com/ shows pages in duplicate ("localbitcoins.com", "animeflv.net").

**Comment by coderobe** [comment]
it's also using an outdated list btw.

**Comment by pathmissing** [comment]
Did not update the tool because there were plenty other tools. This version uses the outdated list.

**Comment by coderobe** [comment]
@sahal2080 bleed.cloud uses an outdated list as well.

**Comment by coderobe** [comment]
Please don't post services here if you don't intend to keep them up to date.  
Thanks in advance.

**Comment by pathmissing** [comment]
Most tools here have been posted before we decided which one to pick.

**Comment by coderobe** [comment]
Well yes, but sites like bleed.cloud have only been added very recently, yet they are using lists from 2 days ago.

**Comment by MiningPickaxe** [comment]
I'm trying to keep my site up to date. Theoretically it should sync it every 30 min, does not work atm, doing it manually as soon as a new version arrives. Currently working on fixing it.

**Comment by coderobe** [comment]
@MiningPickaxe whilst your website does use an up-to-date list, the wording is still a bit unclear IMO.

**Comment by MiningPickaxe** [comment]
If you could help me with that, I would appreciate it. I'm german and english is my secondary language...

**Comment by derinb** [comment]
Hello guys,

I made Firefox and Chrome extension which checks your browser history for the affected websites. If you visited affected websites recently, extension will search and warn you. Check them out please and kindly review.

https://chrome.google.com/webstore/detail/cloudbleed/gmbmbodfgolnnfhfanhjeodfambaoklj
https://addons.mozilla.org/en-US/firefox/addon/cloudbleed/

Thanks

**Comment by coderobe** [comment]
@MiningPickaxe As you may understand, this is kinda out-of-scope here. You can check your site in to git though, allowing people to contribute.

**Comment by MiningPickaxe** [comment]
The code is now avaible here: https://github.com/MiningPickaxe/Cloudbleed-Domain-Checker
Feel free to give feedback, help me with my grammar and spelling or help to add new features/fix bugs

**Comment by mikemrm** [comment]
I made a tool to search your Chrome and FireFox history and compare it to the current list of sites and tell you which sites you've been to are affected. Would appreciate you considering adding it to the list.
https://github.com/mikemrm/CloudFlare-HistoryChecker

**Comment by thislooksfun** [comment]
@mikemrm added!

**Comment by mikemrm** [comment]
Thanks!

**Comment by taltman** [comment]
I created a tool to check your browsing history across several browsers on MacOSX against the list, feedback welcome! https://github.com/taltman/cloudbleed-browser-scan

**Comment by peterrosell** [comment]
Another tool for bulk checking against the list of possible affected sites, https://github.com/peterrosell/cloudbleed-check. It always fetches the master version of the list. To use it you just pipe a file containing hostnames or urls. No external dependencies and can also be run as a docker container.

**Comment by coderobe** [comment]
@peterrosell you mean like `curl -Ls https://git.io/vyT0W | grep -x 'domain.com'`? 😉

**Comment by pirate** [comment]
I'm a little wary of all these Chrome extensions, this list is intended for companies more than individuals.  It will alert if they go on any of 4,000,000+ domains.  There will be too many false positives to make it a useful tool, and by forcing users to reset so many passwords, we're more likely to make them choose poor ones.

**Comment by peterrosell** [comment]
@coderobe more like this: ```echo "select url from urls;" | sqlite3 ~/.config/google-chrome/Default/History | \
    docker run -i --rm peterrosell/cloudbleed-check:latest```
It checks all urls from the input file

**Comment by taltman** [comment]
I've extended my tool for checking browser history on Mac (Safari, Chrome/Chromium, Firefox/TorBrowser) to now output the number of visits (summed across all browsers), and to report the most recent visit date (across all browsers) in addition to the URL, to make it easy to whittle down a large list (in my case, from 359 to 28 domains to manually check). Check it out here: https://github.com/taltman/cloudbleed-browser-scan @thislooksfun, can we add this to the list above? Thanks!

**Comment by taltman** [comment]
OK, cloudbleed-browser-scan now has been ported over to Linux. Would love for some help to get it ported to Windows...

**Comment by Eonasdan** [comment]
@taltman I have a wfp/windows app that does that

**Comment by taltman** [comment]
@Eonasdan Nice! Thanks for pointing it out to me. Does it support browsers on Windows beyond Chrome?

**Comment by mikemrm** [comment]
Additionally. The app that I created above does chrome and Firefox in windows

**Comment by nuvious** [comment]
I wrote a java app for those that have password managers and can generate a list of all the domains they have accounts on. Youtube tutorial in ReadMe.md file.

https://github.com/nuvious/CloudFareDomainSearch

**Comment by smdvw5** [comment]
I hacked together a python script for going over exported Firefox bookmarks (save as 'bookmarks.json') as there is not a Firefox add-on for that at the moment.
Quick export guide: Bookmarks -> Show All Bookmarks -> Import and Backup -> Backup (name it 'bookmarks.json').
Have 'sorted_unique_cf.txt' downloaded in the same folder.
Run 'python3 site_search.py'.
( https://github.com/smdvw5/sites-using-cloudflare/blob/master/site_search.py )

**Comment by Eonasdan** [comment]
@taltman for whatever it's worth at this point.... my app now supports FF

**Comment by pirate** [comment]
Closing this issue, I don't recommend that anyone create new tools to search list list due to having too many false positives.  I'm going to work on archiving this repo, but thanks for everyone's help so far!
