### ISSUE TITLE
Add LICENSE.md

### ISSUE THREAD

**Issue by ravi-sensify** [pirate/sites-using-cloudflare#41]
Please add `LICENSE.md` specifying what people can do with the data from here.

**Comment by basisbit** [comment]
this might be really difficult to do because of different / missing licenses on used sources. but then again, did you read the name of the creator of this repo? 😄

**Comment by coderobe** [comment]
The content of this repository is not really something you can put behind a license.

**Comment by pirate** [comment]
It's intentionally unlicensed.
