### ISSUE TITLE
Please remove robxu9.com - static site.

### ISSUE THREAD

**Issue by robxu9** [pirate/sites-using-cloudflare#44]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Please remove robxu9.com since it's a static website using Github Pages - https://github.com/robxu9/robxu9.github.com
This is me: keybase.io/robxu9

I do use the TLS proxy but since it's a static site, no user data should be compromised.

Thanks!
-----BEGIN PGP SIGNATURE-----
Version: Keybase OpenPGP v2.0.64
Comment: https://keybase.io/crypto

wl4EABEKAAYFAliv2P4ACgkQAWAAgagK5W/uEAEApz/RmnZuIXQYmx05ZR9mA9lR
gYonmk+RlbBuIBiW5LUBAK8rtVNraTpOEiIwK9e6S7RsaQf7yo52/6fFF1tH/DPH
=YnEQ
-----END PGP SIGNATURE-----

**Comment by pirate** [comment]
Perfect, thanks!  Done: d55d5f9

**Comment by robxu9** [comment]
Thanks so much! 👍
