### ISSUE TITLE
Remove PvPCraft.ca, ryke.xyz

### ISSUE THREAD

**Issue by macdja38** [pirate/sites-using-cloudflare#49]
Domains: pvpcraft.ca, ryke.xyz, both owned by me. 

https://keybase.io/macdja38

ryke.xyz while not static does not store user data, it's a little experiment.
pvpcraft.ca uses cloudflare for DNS and while it does store user sessions the site is not proxied through cloudflare as services need to correct directly to the domain. The subdomain bot.pvpcraft.ca also stores sessions but uses oauth with another provider and all sessions from the vulnerable period have been cleared.

**Comment by pirate** [comment]
pvpcraft.ca is running wordpress.  Unforunately it's hard to prove that you didn't have any users besides yourself during the affected period, since you could've deleted them.

Do you think being on this list will significantly affect your site's reputation?  (keep in mind lots of huge sites and banks are on the list, and they'll probably be fine)

**Comment by macdja38** [comment]
@pirate it's running word-press hosted on a server I control. I definitely had users other than me during the effected period but they were not being proxied through cloudflare. As you mentioned this list only checks DNS not proxying being enabled.

**Comment by pirate** [comment]
It's a tough call, I trust you own the site, but I cant really confirm that you didn't have SSL proxying turned on during that period.  So far I've only accepted removals that have proved their sites are static, contain no user data, or were never on cloudflare during that period.

**Comment by macdja38** [comment]
@pirate As I said I have other services running on the domain that can't be proxied through cloudflare, for example a minecraft server (cloudflare can't proxy minecraft)
These sites below all show they were able to connect for the last couple months, many more can be found with similar stats and I have a couple hundred witnesses if you would like.
https://topg.org/server-pvpcraft-id394225
http://minecraft-mp.com/server-s28523
https://minecraftlist.com/servers/pvpcraft.ca
https://mineservers.com/server/H4DtlFA7/pvpcraft-ca-free-tardis-pvp-role-play-server
