### ISSUE TITLE
Remove playlyst.xyz, nikitapek.in, dank.xyz

### ISSUE THREAD

**Issue by indiv0** [pirate/sites-using-cloudflare#50]
**Domains**: playlyst.xyz, nikitapek.in, dank.xyz (all owned by me, playlyst.xyz actually just lapsed)

Sites are static (except dank.xyz) but none of them use CloudFlare SSL termination.

Proof sent to git@nicksweeting.com.

**Comment by pirate** [comment]
Got your proofs :+1:.  Mind submitting a PR?

**Comment by indiv0** [comment]
Sure thing.

**Comment by indiv0** [comment]
Thanks!
