### ISSUE TITLE
please remove sites

### ISSUE THREAD

**Issue by ChelseaStats** [pirate/sites-using-cloudflare#60]
Please remove thechels.co.uk (wordpress blog, only one user, me) and thechels.uk (static site hosted on github).

**Comment by turtledude01** [comment]
I can tell you already he probably wont remove it because its 'wordpress and has a user' he wont remove it unless it has no users and with wordpress/joomla you cant even prove to him that theres only 1/no users...

**Comment by pirate** [comment]
Unfortunately I cant remove the wordpress blog because it's using cloudflare TLS `server:cloudflare-nginx` and it's very hard to prove that you were the only user during the affected period.

I'm happy to remove the github pages one though, just submit a PR.

**Comment by ChelseaStats** [comment]
I can't submit a PR because the filesize is too big from my ipad/iphone or github's uploader

Can you also remove jllpestcontrol.co.uk and catherinesglass.co.uk (both static sites on github I manage)

thanks

**Comment by ravi-sensify** [comment]
I submitted PR #65 for you, @ChelseaStats

**Comment by ChelseaStats** [comment]
thanks very much :-)
