### ISSUE TITLE
Please remove Vigilante.pw

### ISSUE THREAD

**Issue by kevinendicott** [pirate/sites-using-cloudflare#62]
Please remove Vigilante.pw from the list. We do not store any user data and we don't store the breached databases that we report on, either. The website consists of a static page with a list of data breaches.

The same goes for DBDirectory.info and Disappear.today which are just mirrors of the site.

**Comment by pirate** [comment]
No problem, just submit a PR with the changes I'll approve it.

**Comment by kevinendicott** [comment]
Sorry, I'm new to Github and I'm a bit confused as to what I have to do on the "pull request" page.

**Comment by pirate** [comment]
@kevinendicott no worries, I'll do it for you.

**Comment by kevinendicott** [comment]
Thanks :)

**Comment by pirate** [comment]
Done: 525d8a6
