### ISSUE TITLE
Move sorted_unique_cf.txt into Large File Storage (LFS)

### ISSUE THREAD

**Issue by ravi-sensify** [pirate/sites-using-cloudflare#68]
References: 

* https://git-lfs.github.com/
* https://help.github.com/articles/working-with-large-files/

The file `sorted_unique_cf.txt` is already > 50MB, and GitHub recommends pushing it into LFS to improve performance without breaking any functionality.

**Comment by pirate** [comment]
Git LFS replaces the file with a pointer, which makes diffing the contents much harder.  We want to keep diffs easy.  It's only 18mb bigger than the warning size, not worth upgrading to LFS yet.  I'd consider splitting it into alphabetical chunked files though.
