### ISSUE TITLE
Add smartgunlaws.org to affected site list

### ISSUE THREAD

**Issue by koitsu** [pirate/sites-using-cloudflare#71]
See NS records and/or WHOIS data for smartgunlaws.org, as well as below confirmation (look very very closely at the mangled data on the right):

http://webcache.googleusercontent.com/search?q=cache:lw4K9G2F1WgJ:lightnetwork.ph/ofw-family-day-december-1/+&cd=3&hl=en&ct=clnk&gl=us

**Comment by pirate** [comment]
Ah jeez they're not even on HTTPS and they're accepting signup data... shame shame.

**Comment by pirate** [comment]
They're already in the list.
