### ISSUE TITLE
Add: *.leagueoflegends.com

### ISSUE THREAD

**Issue by visualcookie** [pirate/sites-using-cloudflare#77]
Looks like `account.leagueoflegends.com` is also using CloudFlare.

Can't fully confirm, that they use it for everything else, but I just received a message checking for my browser (DDoS prevention system).

**Comment by arunesh90** [comment]
https://account.leagueoflegends.com/cdn-cgi/trace
Can confirm that it uses CloudFlare
Can also confirm that the root domain uses it
https://leagueoflegends.com/cdn-cgi/trace

**Comment by pirate** [comment]
done
