### ISSUE TITLE
duplicate entries

### ISSUE THREAD

**Issue by nickhilliard** [pirate/sites-using-cloudflare#94]
```
% cat sorted_unique_cf.txt | tr '[A-Z]' '[a-z]' | sort | uniq -d | wc -l
    1213
%
```

this should return zero.

**Comment by nevinera** [comment]
Yeah, he documented that he used `| uniq | sort`, which I thought was a typo. A similar (simpler) comparison:

```bash
$ cat sites-using-cloudflare-master/sorted_unique_cf.txt  | sort | uniq | wc -l
 4287625
$ cat sites-using-cloudflare-master/sorted_unique_cf.txt  | wc -l
 4288852
```

**Comment by coderobe** [comment]
I have opened a PR with a fixed version, see https://github.com/pirate/sites-using-cloudflare/pull/99

**Comment by pirate** [comment]
Thanks @coderobe, will merge that shortly and fix the README methodology.
